config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", to: "pages#home"
  devise_scope :user do
    authenticated :user do
      root 'pages#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  namespace :charts do
    get "new-transactions"
  end
  namespace :charts do
    get "cur-transactions"
  end

  # get "/onboarding", to: "pages#onboarding"
  # get "/redirect_preferences", to: "pages#redirect_preferences"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :inc_fiat_accounts, only: [:index]
  resources :user_fiat_accounts
  resources :user_stable_accounts
  resources :transactions, only: [:new, :create, :show, :index]

  resources :users do
    resources :user_stable_account, only: [:show, :index, :update]
  end
end

app/models/inc_stable_account.rb
class IncStableAccount < ApplicationRecord
  has_many :transactions
end

app/controllers/inc_stable_accounts_controller.rb
class IncStableAccountsController < ApplicationController
  before_action :set_inc_stable_account, only: [:show, :edit, :update, :destroy]

  # GET /inc_stable_accounts
  # GET /inc_stable_accounts.json
  def index
    @inc_stable_accounts = IncStableAccount.all
  end

  # GET /inc_stable_accounts/1
  # GET /inc_stable_accounts/1.json
  def show
  end

  # GET /inc_stable_accounts/new
  def new
    @inc_stable_account = IncStableAccount.new
  end

  # GET /inc_stable_accounts/1/edit
  def edit
  end

  # POST /inc_stable_accounts
  # POST /inc_stable_accounts.json
  def create
    @inc_stable_account = IncStableAccount.new(inc_stable_account_params)

    respond_to do |format|
      if @inc_stable_account.save
        format.html { redirect_to @inc_stable_account, notice: 'Inc stable account was successfully created.' }
        format.json { render :show, status: :created, location: @inc_stable_account }
      else
        format.html { render :new }
        format.json { render json: @inc_stable_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inc_stable_accounts/1
  # PATCH/PUT /inc_stable_accounts/1.json
  def update
    respond_to do |format|
      if @inc_stable_account.update(inc_stable_account_params)
        format.html { redirect_to @inc_stable_account, notice: 'Inc stable account was successfully updated.' }
        format.json { render :show, status: :ok, location: @inc_stable_account }
      else
        format.html { render :edit }
        format.json { render json: @inc_stable_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inc_stable_accounts/1
  # DELETE /inc_stable_accounts/1.json
  def destroy
    @inc_stable_account.destroy
    respond_to do |format|
      format.html { redirect_to inc_stable_accounts_url, notice: 'Inc stable account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inc_stable_account
      @inc_stable_account = IncStableAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inc_stable_account_params
      params.fetch(:inc_stable_account, {})
    end
end

app/views/inc_stable_accounts/_form.html.erb
<%= simple_form_for(@inc_stable_account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/inc_stable_accounts/edit.html.erb
<h1>Editing Inc Stable Account</h1>

<%= render 'form', inc_stable_account: @inc_stable_account %>

<%= link_to 'Show', @inc_stable_account %> |
<%= link_to 'Back', inc_stable_accounts_path %>

app/views/inc_stable_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inc Stable Accounts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inc_stable_accounts.each do |inc_stable_account| %>
      <tr>
        <td><%= link_to 'Show', inc_stable_account %></td>
        <td><%= link_to 'Edit', edit_inc_stable_account_path(inc_stable_account) %></td>
        <td><%= link_to 'Destroy', inc_stable_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inc Stable Account', new_inc_stable_account_path %>

app/views/inc_stable_accounts/new.html.erb
<h1>New Inc Stable Account</h1>

<%= render 'form', inc_stable_account: @inc_stable_account %>

<%= link_to 'Back', inc_stable_accounts_path %>

app/views/inc_stable_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inc_stable_account_path(@inc_stable_account) %> |
<%= link_to 'Back', inc_stable_accounts_path %>