config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", to: "pages#home"
  devise_scope :user do
    authenticated :user do
      root 'pages#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  namespace :charts do
    get "new-transactions"
  end
  namespace :charts do
    get "cur-transactions"
  end

  # get "/onboarding", to: "pages#onboarding"
  # get "/redirect_preferences", to: "pages#redirect_preferences"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :inc_fiat_accounts, only: [:index]
  resources :user_fiat_accounts
  resources :user_stable_accounts
  resources :transactions, only: [:new, :create, :show, :index]

  resources :users do
    resources :user_stable_account, only: [:show, :index, :update]
  end
end

app/models/user_fiat_account.rb
class UserFiatAccount < ApplicationRecord
  belongs_to :user
  has_many :transactions
  validate :account_limits
  validates :currency_code, inclusion: { in: %w(EUR USD PHP HRK HKD GBP RUB BRL EUR),
      message: "Tu te crois malin?" }

    def account_limits
      !UserFiatAccount.where(user: self.user).any?{|e| e.currency_code == self.currency_code}
    end
end

app/controllers/user_fiat_accounts_controller.rb
class UserFiatAccountsController < ApplicationController
  before_action :set_user_fiat_account, only: [:show, :edit, :update, :destroy]

  # GET /user_fiat_accounts
  # GET /user_fiat_accounts.json
  def index
    @user_fiat_accounts = UserFiatAccount.all
  end

  # GET /user_fiat_accounts/1
  # GET /user_fiat_accounts/1.json
  def show
  end

  # GET /user_fiat_accounts/new
  def new
    @user_fiat_account = UserFiatAccount.new
  end

  # GET /user_fiat_accounts/1/edit
  def edit
  end

  # POST /user_fiat_accounts
  # POST /user_fiat_accounts.json
  def create
    @user_fiat_account = UserFiatAccount.new
    @user_fiat_account.currency_code = user_fiat_account_params[:currency_code]
    @user_fiat_account.amount = user_fiat_account_params[:amount].to_f
    @user_fiat_account.user = current_user

    respond_to do |format|
      if @user_fiat_account.save
        UserStableAccount.create(user: current_user, amount: 0.0) if UserStableAccount.where(user: current_user).empty?
        format.html { redirect_to home_path, notice: 'User fiat account was successfully created.' }
        format.json { render :show, status: :created, location: @user_fiat_account }
      else
        format.html { render :new }
        format.json { render json: @user_fiat_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_fiat_accounts/1
  # PATCH/PUT /user_fiat_accounts/1.json
  def update
    respond_to do |format|
      if @user_fiat_account.update(user_fiat_account_params)
        format.html { redirect_to @user_fiat_account, notice: 'User fiat account was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_fiat_account }
      else
        format.html { render :edit }
        format.json { render json: @user_fiat_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_fiat_accounts/1
  # DELETE /user_fiat_accounts/1.json
  def destroy
    @user_fiat_account.destroy
    respond_to do |format|
      format.html { redirect_to user_fiat_accounts_url, notice: 'User fiat account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_fiat_account
      @user_fiat_account = UserFiatAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_fiat_account_params
      params.fetch(:user_fiat_account, {})
    end
end

app/views/user_fiat_accounts/_form.html.erb
<%= simple_form_for(@user_fiat_account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <% @currencies = ["EUR", "USD", "PHP", "HRK", "HKD", "GBP", "RUB", "BRL", "EUR"] %>
    <%= f.input :currency_code, label: "Wire money in your wallet", as: :select, collection: @currencies,  wrapper: :vertical_collection_inline, selected: @currencies[0] %>
    <%= f.text_field :amount, placeholder: "Amount" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-primary"  %>
  </div>
<% end %>

app/views/user_fiat_accounts/_myaccount.html.erb
  <div class="row my-account-section">
    <h2 class="btn my-account-dividor btn-block">Your Accounts</h2>
    <div class="container accounts-recap">
      <div class="row">
        <div class="col-xs-12 col-sm-6 container card-presentation">
          <div class="card-header">
            <h4>Your FIAT accounts</h4>
          </div>
          <div class="card-content">
            <table>
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% UserFiatAccount.where(user: current_user).each do |account| %>
                  <tr>
                    <td class="highlited-amount fiat-currency-display"><h3><%= number_to_currency_br(account.amount) %></h3></td>
                    <td class="highlited-amount fiat-currency-display"><h3><%= account.currency_code %></h3></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="transaction-fiat">
              <h4>Make a Transfer</h4>
              <%= render 'transactions/buyform', transaction: @transaction, locals: {typetr: "BUY"} %>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-sm-6 container card-presentation">
          <div class="card-header">
            <h4>Your STABLE account</h4>
          </div>
          <% stable_account = UserStableAccount.where(user: current_user)[0] %>
          <div class="card-content">
            <div class="highlited-amount">
            <h3><%= "#{number_to_currency_br(stable_account.amount)} STABLE" %></h3>
            </div>
            <br>
            <h4>Make a Transfer</h4>
            <%= render 'transactions/sellform', transaction: @transaction, locals: {typetr: "SELL"} %>
          </div>
        </div>

      </div>
    </div>
  </div>

app/views/user_fiat_accounts/edit.html.erb
<h1>Editing User Fiat Account</h1>

<%= render 'form', user_fiat_account: @user_fiat_account %>

<%= link_to 'Show', @user_fiat_account %> |
<%= link_to 'Back', user_fiat_accounts_path %>

app/views/user_fiat_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Fiat Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Account ID</th>
      <th>Currency</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_fiat_accounts.each do |user_fiat_account| %>
      <tr>
        <td><%= user_fiat_account.id %></td>
        <td><%= user_fiat_account.currency_code %></td>
        <td><%= user_fiat_account.amount %></td>
        <td><%= link_to 'Show', user_fiat_account %></td>
        <td><%= link_to 'Edit', edit_user_fiat_account_path(user_fiat_account) %></td>
        <td><%= link_to 'Destroy', user_fiat_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Fiat Account', new_user_fiat_account_path %>

app/views/user_fiat_accounts/new.html.erb
<h1>New User Fiat Account</h1>

<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1IStlzzn70abbKkzdhdRRJq4SBB6c-vQ1" width="640" height="480"></iframe>

app/views/user_fiat_accounts/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= @user_fiat_account.currency_code %> <%= @user_fiat_account.amount %></p>

<%= link_to 'Edit', edit_user_fiat_account_path(@user_fiat_account) %> |
<%= link_to 'Back', user_fiat_accounts_path %>